name: fuzz
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang
        run: sudo apt-get install -y clang
      - name: fuzz
        run: |
          cmake --preset linux-test -DBUILD_SHARED_LIBS=on
          cmake --build --preset linux-test --target sear
          cmake --build --preset linux-test --target fuzz
          ASAN_OPTIONS=alloc_dealloc_mismatch=1 build/linux/fuzz -runs=65536
